[package]
name = "shader-language-server"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cfg-if = "1.0.0"
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
log = "0.4.21"
wasm-bindgen = "0.2.92"
wee_alloc = "0.4.5"
