name: Build Extension

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    # Build WASM from source.
    steps:
      - uses: actions/checkout@v4
      - uses: robinraju/release-downloader@v1.11
        with:
          repository: 'WebAssembly/wasi-sdk'
          tag: 'wasi-sdk-22'
          fileName: 'wasi-sysroot-22.0.tar.gz'
          extract: true
      - run: echo "WASI_SYSROOT=$(echo $GITHUB_WORKSPACE)/wasi-sysroot/" >> $GITHUB_ENV
      - run: echo $WASI_SYSROOT
      - run: ls -f $WASI_SYSROOT
      - run: clang --version
      - name: Add target
        run: rustup target add wasm32-wasi
      - name: Build WASI
        working-directory: ./shader-language-server
        run: cargo build --release --target wasm32-wasi --verbose
      #- name: Run tests
      #  working-directory: ./shader-language-server
      #  run: cargo test --target wasm32-wasi --verbose
      - name: Copy file
        run: mkdir -p ./shader-language-server/pkg/ && cp ./shader-language-server/target/wasm32-wasi/release/shader_language_server.wasm ./shader-language-server/pkg/shader_language_server.wasm
      - name: Install dependencies
        run: npm ci
      - name: Install VSCE
        run: npm i -g vsce
      - name: Package extension
        run: vsce package
      - name: Copy VSIX
        run: cp ./hlsl-0.0.1.vsix ./shader-language-server/pkg/hlsl-0.0.1.vsix
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./shader-language-server/pkg/