name: Build Extension

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: npm ci
      - name: Install VSCE
        run: npm i -g vsce
      - name: Package extension
        run: vsce package
      - name: Copy VSIX
        run: mkdir -p ./ext/ && cp ./hlsl-0.0.1.vsix ./ext/hlsl-0.0.1.vsix
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./ext/